### PR TITLE
adapt changes in ghc 9.2

### PR DESCRIPTION
**Pull request by tek**

### CODE REVIEW

**Comment by coderfromhere** [comment]
I've just stumbled on the same incompatibility on GHC 9.2.2:

```
Configuring library for ptr-0.16.8.1..
Preprocessing library for ptr-0.16.8.1..
Building library for ptr-0.16.8.1..
[ 1 of 14] Compiling Ptr.Prelude      ( library/Ptr/Prelude.hs, dist/build/Ptr/Prelude.o, dist/build/Ptr/Prelude.dyn_o )
[ 2 of 14] Compiling Ptr.List         ( library/Ptr/List.hs, dist/build/Ptr/List.o, dist/build/Ptr/List.dyn_o )
[ 3 of 14] Compiling Ptr.Receive.Core ( library/Ptr/Receive/Core.hs, dist/build/Ptr/Receive/Core.o, dist/build/Ptr/Receive/Core.dyn_o )
[ 4 of 14] Compiling Ptr.UncheckedShifting ( library/Ptr/UncheckedShifting.hs, dist/build/Ptr/UncheckedShifting.o, dist/build/Ptr/UncheckedShifting.dyn_o )

library/Ptr/UncheckedShifting.hs:65:36: error:
    • Couldn't match expected type ‘Word16#’ with actual type ‘Word#’
    • In the first argument of ‘W16#’, namely
        ‘(w `uncheckedShiftRL#` i)’
      In the expression: W16# (w `uncheckedShiftRL#` i)
      In an equation for ‘shiftr_w16’:
          shiftr_w16 (W16# w) (I# i) = W16# (w `uncheckedShiftRL#` i)
   |
65 | shiftr_w16 (W16# w) (I# i) = W16# (w `uncheckedShiftRL#`   i)
   |                                    ^^^^^^^^^^^^^^^^^^^^^^^^^

library/Ptr/UncheckedShifting.hs:66:36: error:
    • Couldn't match expected type ‘Word32#’ with actual type ‘Word#’
    • In the first argument of ‘W32#’, namely
        ‘(w `uncheckedShiftRL#` i)’
      In the expression: W32# (w `uncheckedShiftRL#` i)
      In an equation for ‘shiftr_w32’:
          shiftr_w32 (W32# w) (I# i) = W32# (w `uncheckedShiftRL#` i)
   |
66 | shiftr_w32 (W32# w) (I# i) = W32# (w `uncheckedShiftRL#`   i)
   |                                    ^^^^^^^^^^^^^^^^^^^^^^^^^
cabal: Failed to build ptr-0.16.8.1
```

**Comment by arrowd** [comment]
Can we have this in and then a new Hackage release?

**Comment by robx** [comment]
For reference, the change seems to be this: https://downloads.haskell.org/ghc/9.2.2/docs/html/users_guide/9.2.1-notes.html#base-library:

Instead of pre-9.2

```
data Word16 = W16# Word#
```

it's now

```
data Word16 = W16# Word16#
```

The change looks good to me.

**Comment by tek** [comment]
@nikita-volkov did you see this?

**Comment by nikita-volkov** [comment]
Oops. Sorry. For some reason I wasn't subscribed to activity in this repo. Thanks for the mention and the PR, @tek! I'll merge this right away.

**Comment by nikita-volkov** [comment]
Released as 0.16.8.2

**Comment by tek** [comment]
damn :smile:

**Pull request merged**
